### ISSUE TITLE
comment BSD/GNU utils differences

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/shellstyle#3]
Example of different behaviors:
- [ ] find
- [ ] mktemp
- [ ] sed
- [ ] echo
- [ ] seq
- [ ] ...

**Comment by caarlos0** [comment]
@aureliojargas would like to help here?

**Comment by aureliojargas** [comment]
Yep, here is a good source: https://github.com/funcoeszz/funcoeszz/wiki/Portabilidade
